/**
 * This file is overwritten by `npm run build` (Vite).
 * Source of truth: src/wallet-permit2.js
 * Do not edit this file by hand — it will be replaced on deploy.
 *
 * Until the first build runs, the page will fail to load AppKit.
 * Run: npm install && npm run build
 */
console.error(
  '[wallet-permit2] Bundle missing. Run npm install && npm run build, then redeploy.'
);
